### PR TITLE
Fix Creating Page shows up in Post list 

### PR DESCRIPTION
**Pull request by juacompe**
## Problem

Creating a new page shows up in Post list
## Repro steps:
1. create a story
2. be redirected to profile page
3. click on 'Your Pages' tag

observed:
- You have not created any pages yet.

expected:
- newly created Story
## Change summary:
1. add syntax hilighting and a prerequisite (installing reddis) `README.md`
2. ignore `*.pyc` (for vim)
3. add `django-nose` version 1.2 (for development environment)
4. add `Content` as an abstract model class
5. make both `Story` and `Post` inherits from `Content`
6. makes the `StoryForm.Meta` inherits from `PostForm.Meta`
7. update `blog_sync` rq job to also generate stories
8. update `profile.html` template so that Your Page tab is as pretty as Your Post tab

### CODE REVIEW

**Comment by ralsina** [comment]
The changes look good, but the description is sort of misleading ;-)

**Comment by juacompe** [comment]
@ralsina Thanks for the comment! Can you help me finding the misleading description you mentioned? I'm not sure which file you were talking about? (-___- )a

Thanks in advance!

**Comment by ralsina** [comment]
The commit message is "Make README easier to read." but the branch really touches a ton of other stuff. It probably should be split into different pulls or be given a more complete message like "merge all these things: foo bar baz"

**Comment by juacompe** [comment]
I updated my request. Sorry for the misleading description. This is my first pull request on Github. :P

**Comment by ralsina** [comment]
@juacompe don't worry, it _is_ weird the first few times :-)

Anyway, thanks for the effort, merging!

**Comment by ralsina** [comment]
BTW, I just deployed these changes in donewithniko.la :-)

**Comment by ralsina** [comment]
Looks like this change totally broke my deployment :-(

I am now getting "Unknown column 'blogs_story.id' in 'field list'" everywhere, I am assuming some change in the model was not reflected in a migration or something.

**Comment by ralsina** [comment]
Looks like I need to be much more careful about merging branches. Why on earth did you delete all migrations? It totally breaks everything :-(

Any ideas on how to fix this?

**Comment by ralsina** [comment]
Oh well, everything is so screwed up I see no way to fix it. Shutting down the server I guess.

**Comment by ralsina** [comment]
I have merged most of the individual commits, perhaps we can find a way to introduce the missing bits now. Or perhaps since all data is gone, it doesn't matter.

**Comment by juacompe** [comment]
Originally, the Story model was inherited from Post. In that case, the Story table in the database had only a foreign key to Post table and all Story data are stored in Post table.

That's why blog.post_set.all() returns all post and story.

I changed the Story and Post models to inherit from an abstract class named Content. After the change, the Story table in the database now contain all the fields as the Post table does.

To migrate this change, we need to move the stories that was in Post table into Story table. I couldn't find a way to make that automated migration step with South.

Any suggestions how we can make that migration step?

**Comment by ralsina** [comment]
On 07/08/13 20:00, juacompe wrote:

> Originally, the Story model was inherited from Post. In that case, the
> Story table in the database had only a foreign key to Post table and
> all Story data are stored in Post table.
> 
> That's why blog.post_set.all() returns all post and story.
> 
> I changed the Story and Post models to inherit from an abstract class
> named Content. After the change, the Story table in the database now
> contain all the fields as the Post table does.
> 
> To migrate this change, we need to move the stories that was in Post
> table into Story table. I couldn't find a way to make that automated
> migration step with South.

I am far from a south expert, so I don't know if this is even possible.
Just pretty please, the next time your do a PR that breaks every
existing installation, say so in the request :-)

> Any suggestions how we can make that migration step?

I suppose now we can just break it since all the data is gone anyway.

**Comment by juacompe** [comment]
I tried putting in commit message of f005a87 but apparently that is not as visible as it should be. I am sorry that my change caused you to lose all the data. :'(

Next time I'll mention it first thing in my pull request. I won't let this happen again.

**Comment by juacompe** [comment]
I see that http://donewithniko.la/ is still down. The site instance is missing. Did you create the database with command `python manage.py syncdb --all`? During that step you should be prompt for adding a superuser. That step should create both super user and a site instance (derived from the email of the superuser). 

You can also create a site instance via django shell >> http://stackoverflow.com/a/11814271/857931

**Comment by ralsina** [comment]
On 07/08/13 22:24, juacompe wrote:

> I see that http://donewithniko.la/ is still down. The site instance is
> missing. Did you create the database with command |python manage.py
> syncdb --all|? During that step you should be prompt for adding a
> superuser. That step should create both super user and a site instance
> (derived from the email of the superuser).
> 
> You can also create a site instance via django shell >>
> http://stackoverflow.com/a/11814271/857931

I'll not bring it up until it's more mature.

**Pull request merged**
